[package]
name = "wcs-bot"
version = "0.1.0"
edition = "2018"

[dependencies.tokio]
version = "1.0"
features = ["macros", "signal", "rt-multi-thread"]

[dependencies.serenity]
version = "0.10.0"
features = ["cache", "framework", "standard_framework", "rustls_backend"]
